CREATE USER zf_nih@localhost IDENTIFIED BY 'zf_nih';
GRANT USAGE ON *.* TO zf_nih@localhost
    REQUIRE NONE
    WITH MAX_QUERIES_PER_HOUR 0
    MAX_CONNECTIONS_PER_HOUR 0
    MAX_UPDATES_PER_HOUR 0
    MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS zf_nih;
GRANT ALL PRIVILEGES ON zf_nih.* TO zf_nih@localhost;

