INSERT INTO mutation_type (id, name, abbrv, description) VALUES (1, 'Deletion', 'Del', 'a deletion of sequences between two induced double-strand breaks or by homologous recombination.');
INSERT INTO mutation_type (id, name, abbrv, description) VALUES (2, 'Enhancer Trap', 'Et', 'insertion of exogenously provided sequences outside the coding sequence of a gene, resulting in reporter expression.');
INSERT INTO mutation_type (id, name, abbrv, description) VALUES (4, 'InDel', 'InDel', 'a small insertion or deletion that changes the reading frame of the mRNA, typically induced at the site of a single targeted double-strand break.');
INSERT INTO mutation_type (id, name, abbrv, description) VALUES (5, 'Gene Trap', 'Gt', 'insertion of exogenously provided sequences inside the coding sequence of a gene, resulting in a fusion transcript.');
INSERT INTO mutation_type (id, name, abbrv, description) VALUES (6, 'Missense', 'Mis', 'a single nucleotide change that changes an amino acid in the coding sequence of a gene.');
INSERT INTO mutation_type (id, name, abbrv, description) VALUES (7, 'Nonsense', 'Stop', 'a single nucleotide change that creates a TAG, TAA or TGA codon in the coding sequence of a gene.');
INSERT INTO mutation_type (id, name, abbrv, description) VALUES (9, 'Splice site', 'Spl', 'a nucleotide change that disrupts the sequence of a splice donor or splice acceptor.');
INSERT INTO mutation_type (id, name, abbrv, description) VALUES (13, 'Random Insertion', 'Ins (ran)', 'non-targeted insertion of exogenously provided sequences causing a disruption of gene function');
INSERT INTO mutation_type (id, name, abbrv, description) VALUES (14, 'Targeted insertion', 'Ins (tar)', 'targeted insertion of a marker or loxP element into a gene using homology-mediated mechanisms');
INSERT INTO mutation_type (id, name, abbrv, description) VALUES (19, 'Point', 'Point', 'Please map to the specific type of point mutation');
INSERT INTO mutation_type (id, name, abbrv, description) VALUES (20, 'Spontaneous', 'sp', 'Spontaneous mutation');
INSERT INTO mutation_type (id, name, abbrv, description) VALUES (21, 'Insertion', 'Ins', 'Please change to Random Insertion or Targeted Insertion.');
